logging:
  config: classpath:logback.xml
camel:
  springboot:
    name: hello-world-camel
    main-run-controller: true
server:
  address: 0.0.0.0
management:
  server:
    address: 0.0.0.0
endpoints:
  enabled: false
  health:
    enables: true